### ISSUE TITLE
Mock not working properly?

### ISSUE THREAD

**Issue by gottfrois** [teamon/tesla#140]
Hey guys,

Following the readme, I've added the following mock:

```elixir
setup do
  Tesla.Mock.mock fn
    %{method: :post, url: "http://foo.com"} ->
      %Tesla.Env{status: 200, body: "hi!"}
  end

  :ok
end
```

Using the following abstraction:

```elixir
defmodule Notifications.Webhooks.Http do
  use Tesla, only: [:post]

  plug Tesla.Middleware.Tuples
  plug Tesla.Middleware.Retry, delay: 1_000, max_retries: 5
  plug Tesla.Middleware.FollowRedirects
  plug Tesla.Middleware.Timeout, timeout: 5_000
  plug Tesla.Middleware.Logger

  def send(url, headers, body) do
    case post(url, body, headers: headers) do
      {:ok, env}        -> {:ok, %{status: env.status, body: env.body, headers: env.headers}}
      {:error, reason}  -> {:error, reason.message}
    end
  end
end
```

But for some reasons, the test fails with:

```
1) test successfuly sending a webhook should create a new delivery (Notifications.WebhookTest)
     test/notifications/webhooks/webhook_test.exs:25
     ** (Tesla.Mock.Error) There is no mock set for process #PID<0.321.0>.
     Use Tesla.Mock.mock/1 to mock HTTP requests.

     See https://github.com/teamon/tesla#testing

     code: Notifications.send(@webhook)
     stacktrace:
       (tesla) lib/tesla/middleware/timeout.ex:55: Tesla.Middleware.Timeout.repass_error/1
       (tesla) lib/tesla/middleware/timeout.ex:35: Tesla.Middleware.Timeout.call/3
       (tesla) lib/tesla/middleware/follow_redirects.ex:40: Tesla.Middleware.FollowRedirects.redirect/3
       (tesla) lib/tesla/middleware/retry.ex:39: Tesla.Middleware.Retry.retry/4
       (tesla) lib/tesla/middleware/tuples.ex:41: Tesla.Middleware.Tuples.call/3
       (notifications) lib/notifications/webhooks/http.ex:11: Notifications.Webhooks.Http.send/3
       (notifications) lib/notifications/webhooks/webhook.ex:19: Notifications.Protocol.Notifications.Webhooks.Webhook.send/1
       test/notifications/webhooks/webhook_test.exs:26: (test)
```

I'm using `v0.9.0`.

**Comment by pawelduda** [comment]
I have reproduced your case but then checked https://github.com/teamon/tesla/pull/136 by @Zorbash and it fixes it :)

**Comment by Daniel-Xu** [comment]
I have the same issue:

```
  def delete_invitation_task(interview) do
    Task.Supervisor.async_nolink(InterviewsApi.TaskSupervisor, fn ->
      InterviewsApi.Caldav.delete_event(interview)
    end)
  end
```

the request is made in a Task process, this `delete_invitation_task` is called in `controller` `delete` action
but when I run the acceptance test (controller test), the mock doesn't capture the request.

@gottfrois @pawelduda how did you fix the issue?

**Comment by Zorbash** [comment]
@Daniel-Xu 
You can define your mock adapter using the code from #136 

https://raw.githubusercontent.com/Zorbash/tesla/deep-mock/lib/tesla/mock.ex

and then use `Application.put_env(:tesla, :adapter, YourMockModule)`

**Comment by Daniel-Xu** [comment]
@Zorbash Thanks for your reply.

**Comment by teamon** [comment]
Please take a look at #143
