### ISSUE TITLE
Trying to mock request but getting  ** (ArgumentError) argument error

### ISSUE THREAD

**Issue by digitalcake** [teamon/tesla#152]
Error
```
 ** (ArgumentError) argument error

     stacktrace:
       :erlang.iolist_to_binary([%{"lat" => "45.4907929", "lon" => "-122.6208822"}])
       (tesla) lib/tesla/middleware/core.ex:31: Tesla.Middleware.Normalize.normalize_body/1
       (elixir) lib/map.ex:732: Map.update!/3
       (tesla) lib/tesla/middleware/json.ex:50: Tesla.Middleware.JSON.call/3
       (come_bike) lib/come_bike/nominatim_openstreetmap_api.ex:8: ComeBike.NominatimOpenstreetmapApi.get_lat_log/4
```

my setup mock:

```
setup %{conn: conn} do
    Tesla.Mock.mock(fn
      %{method: :get, url: "http://api.geonames.org/timezoneJSON"} ->
        %Tesla.Env{
          url: "http://nominatim.openstreetmap.org/search",
          status: 200,
          body: [
            %{
              "rawOffset" => -8,
              "timezoneId" => "America/Los_Angeles"
            }
          ]
        }
    end)
```

Looks to be happening from ` {k |> to_string |> String.downcase(), v |> to_string} ` of
```
def normalize_headers(headers) when is_map(headers) or is_list(headers) do
    Enum.into(headers, %{}, fn {k, v} ->
      {k |> to_string |> String.downcase(), v |> to_string}
    end)
  end
```

**Comment by digitalcake** [comment]
Thank you @teamon that was the solution I was looking for.
