### ISSUE TITLE
Compilation error in Tesla.build_client/1

### ISSUE THREAD

**Issue by nicolasgarnil** [teamon/tesla#168]
## branch: 1.0-tuples

Seems like `Tesla.build_client/1` doesn't accept expressions as an argument.

## Example

```elixir
require Tesla

@default_middlewares [
  {Tesla.Middleware.Headers, [{"accept-language", "es"}]}
]

def new(middlewares \\ []) do
  Tesla.build_client(@default_middlewares ++ middlewares)
end
```

## Error

```bash
$ mix test
Compiling 1 file (.ex)

== Compilation error in file lib/driver/clients/ruby_core/ruby_core.ex ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:++, [line: 15], [[{{:__aliases__, [line: 14, counter: -576460752303422943], [:Tesla, :Middleware, :Headers]}, [{"accept-language", {{:., [line: 14], [{:__aliases__, [line: 14, counter: -576460752303422943], [:Gettext]}, :get_locale]}, [line: 14], [{:__aliases__, [line: 14, counter: -576460752303422943], [:Driver, :Gettext]}]}}]}], {:middlewares, [line: 15], nil}]}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:1919: Enum.map/2
    lib/tesla/builder.ex:389: Tesla.Builder.compile_context/2
    expanding macro: Tesla.Builder.client/2
    lib/driver/clients/ruby_core/ruby_core.ex:13: Driver.Client.RubyCore.new/1
    expanding macro: Tesla.build_client/1
    lib/driver/clients/ruby_core/ruby_core.ex:13: Driver.Client.RubyCore.new/1
```

**Comment by teamon** [comment]
Solved in dee14de
