### ISSUE TITLE
No matching clause error when using DigestAuth

### ISSUE THREAD

**Issue by adkron** [teamon/tesla#298]
The DigestAuth is sending `nil` into `Tesla.put_headers/2`. I know that I can get it to work by forcing `Tesla.put_headers/2` to convert nils to an empty list, but I wasn't sure if that was the best way or if it should be taken care of higher in the stack.

~~~elixir
** (FunctionClauseError) no function clause matching in Tesla.put_headers/2

    The following arguments were given to Tesla.put_headers/2:

        # 1
        %Tesla.Env{
          __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
          __module__: Axis,
          body: nil,
          headers: [],
          method: :get,
          opts: [digest_auth_handshake: true],
          query: [],
          status: nil,
          url: "http://192.168.1.189/some_path.cgi"
        }

        # 2
        nil

    Attempted function clauses (showing 1 out of 1):

        def put_headers(%Tesla.Env{} = env, list) when is_list(list)

    (tesla) lib/tesla.ex:416: Tesla.put_headers/2
    (tesla) lib/tesla/middleware/core.ex:66: Tesla.Middleware.Headers.call/3
    (tesla) lib/tesla/middleware/digest_auth.ex:57: Tesla.Middleware.DigestAuth.authorization_vars/2
    (tesla) lib/tesla/middleware/digest_auth.ex:47: Tesla.Middleware.DigestAuth.authorization_header/2
    (tesla) lib/tesla/middleware/digest_auth.ex:38: Tesla.Middleware.DigestAuth.call/3
~~~

**Comment by teamon** [comment]
closing as #299 is closed
