### ISSUE TITLE
Hackney adapter does not handle {:error, :closed} returned by :hackeny.send_body/2

### ISSUE THREAD

**Issue by tbhavs** [teamon/tesla#314]
I am getting random `{:error, :closed}` from `:hackeny.send_body/2` and Tesla.client crashes with following stack trace.

```
 {:EXIT, #PID<0.23655.28>, {{:badmatch, {:error, :closed}}, [{
Tesla.Adapter.Hackney, :"-request_stream/5-fun-0-", 3, [file: 'lib/tesla/adapter/hackney.ex', line: 74]}, 
{Enum, :"-reduce/3-anonymous-2-", 3, [file: 'lib/enum.ex', line: 3015]}, 
{Stream, :do_transform_each, 3, [file: 'lib/stream.ex', line: 966]}, 
{Stream, :do_resource, 5, [file: 'lib/stream.ex', line: 1394]}, 
{Stream, :do_enum_transform, 7, [file: 'lib/stream.ex', line: 936]}, 
{Enum, :reduce, 3, [file: 'lib/enum.ex', line: 3015]}, 
{Tesla.Adapter.Hackney, :request_stream, 5, [file: 'lib/tesla/adapter/hackney.ex', line: 74]}, 
{Tesla.Adapter.Hackney, :call, 2, [file: 'lib/tesla/adapter/hackney.ex', line: 31]}
]}}
```

```
** (MatchError) no match of right hand side value: {:error, :closed}
(tesla) lib/tesla/adapter/hackney.ex:74: anonymous fn/3 in Tesla.Adapter.Hackney.request_stream/5
(elixir) lib/enum.ex:3015: anonymous fn/3 in Enum.reduce/3
(tesla) lib/tesla/adapter/hackney.ex:31: Tesla.Adapter.Hackney.call/2
(elixir) lib/stream.ex:1394: Stream.do_resource/5
(tesla) lib/tesla/adapter/hackney.ex:74: anonymous fn/3 in Tesla.Adapter.Hackney.request_stream/5
(elixir) lib/stream.ex:936: Stream.do_enum_transform/7
```

I am trying to make a `POST` request using `Tesla.post` using Tesla.Multipart body. 
**Method:** :post
**URL:** "server url"
**Headers:** [
  {"authorization", "Bearer <token>"},
  {"content-type", "multipart/form-data; boundary=<end_string>; charset=utf-8"}
]
**Opts:** [recv_timeout: 1800000]
**Multipart body:** 
```
Multipart.new
    |> Multipart.add_content_type_param("charset=utf-8")
    |> Multipart.add_field("field", <encoded_field_data>)
    |> Multipart.add_file(<path>,
         name: "filename",
         filename: Path.basename(<path>),
         headers: [{"content-type", "application/octet-stream"}]
       )
```

**Comment by tbhavs** [comment]
I have updated the correct debug stacktrace now.

**Comment by teamon** [comment]
[Yep.](https://github.com/teamon/tesla/blob/master/lib/tesla/adapter/hackney.ex#L75)

**Comment by Dreat** [comment]
I have no idea how to make proper test for that, but I will soon give you a PR with a fix :)
