### ISSUE TITLE
Wrong type specification for the status field in the Tesla.Env struct

### ISSUE THREAD

**Issue by igor-i** [teamon/tesla#348]
Because the Tesla.Env struct is used for both requests and responses (in the 1st argument in the Tesla.Adapter.call/2), its status field can be nil, yet its type is defined as integer.

We have an error because of this when checking the type definition.

**Comment by teamon** [comment]
@igor-i Can you share an example?

**Comment by igor-i** [comment]
@teamon We use [this library](https://github.com/msz/hammox) for mocking the Tesla client with automatic contract testing. This is the error we are getting:

```  1) test returns :ok on success (AuthBackend.ExternalApi.MCPTest)
     test/auth_backend/external_api/mcp_test.exs:6
     ** (Hammox.TypeMatchError)
     1st argument value %Tesla.Env{__client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: [{Tesla.Middleware.JSON, :call, [[]]}, {Tesla.Middleware.BasicAuth, :call, [%{password: nil, username: "user"}]}, {Tesla.Middleware.BaseUrl, :call, ["https://someurl.io/"]}]}, __module__: AuthBackend.ExternalApi.MCP, body: nil, headers: [{"authorization", "Basic dcjo="}], method: :get, opts: [adapter: [connect_timeout: 8000, timeout: 5000]], query: [msisdn: "79000000000"], status: nil, url: "https://someurl.io"} does not match 1st parameter's type Tesla.Env.t() ("env").
       Map value nil for key :status does not match map value type Tesla.Env.status().
         Value nil does not match type integer().
     code: assert :ok = MCP.init_profile("79000000000")
     stacktrace:
       (hammox) lib/hammox.ex:273: Hammox.check_call/3
       (hammox) lib/hammox.ex:256: Hammox.protected_code/3
       (tesla) lib/tesla/middleware/json.ex:52: Tesla.Middleware.JSON.call/3
       (auth_backend) lib/auth_backend/external_api/mcp.ex:24: AuthBackend.ExternalApi.MCP.init_profile/1
       test/auth_backend/external_api/mcp_test.exs:15: (test)```

**Comment by teamon** [comment]
@igor-i Could you try changing the typespec to `integer | nil` and see if that fixes the contract tests?

**Comment by igor-i** [comment]
@teamon Yes, that fixed the contract tests.

**Comment by teamon** [comment]
Fixed in https://github.com/teamon/tesla/pull/349
